# Generated by Django 5.0.6 on 2026-06-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('email', 'Email')], max_length=20, unique=True)),
                ('settings', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'System settings',
                'db_table': 'system_settings',
            },
        ),
    ]
