# Generated by Django 5.0.6 on 2026-06-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'tenants',
                'indexes': [models.Index(fields=['status'], name='tenants_status_80d9b6_idx'), models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['is_deleted', 'status'], name='tenants_is_dele_885497_idx')],
            },
        ),
    ]
